# Generated by Django 3.2.4 on 2021-06-11 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maihomstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catigories',
            name='categoriesdetail',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='productdetail',
            field=models.TextField(max_length=255),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='uploads/')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='maihomstore.product')),
            ],
        ),
    ]
